-- create Order Table with constraints
CREATE TABLE ORDERS(
	O_ORDERKEY INTEGER NOT NULL PRIMARY KEY,
	O_CUSTKEY INTEGER NOT NULL,
	O_ORDERSTATUS CHAR(1),
	O_TOTALPRICE DECIMAL NOT NULL CHECK (O_TOTALPRICE >= 0),
	O_ORDERDATE DATE,
	O_ORDERPRIORITY CHAR(15),
	O_CLERK CHAR(15),
	O_SHIPPRIORITY INTEGER,
	O_COMMENT VARCHAR(79),
	FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY),
	CONSTRAINT check_pk_orderkey CHECK (O_ORDERKEY >= 0)
);