-- create Part Table with constraints
CREATE TABLE PART(
	P_PARTKEY INTEGER NOT NULL PRIMARY KEY,
	P_NAME VARCHAR(55),
	P_MFGR CHAR(25),
	P_BRAND CHAR(10),
	P_TYPE VARCHAR(25),
	P_SIZE INTEGER NOT NULL CHECK (P_SIZE >= 0),
	P_CONTAINER CHAR(10),
	P_RETAILPRICE DECIMAL NOT NULL CHECK (P_RETAILPRICE >= 0),
	P_COMMENT VARCHAR(23),
	CONSTRAINT check_pk_part CHECK (P_PARTKEY >= 0)
	);