-- create Partsupp Table with constraints
CREATE TABLE PARTSUPP(
	PS_PARTKEY INTEGER NOT NULL,
	PS_SUPPKEY INTEGER NOT NULL,
	PS_AVAILQTY INTEGER NOT NULL CHECK (PS_AVAILQTY >= 0),
	PS_SUPPLYCOST DECIMAL NOT NULL CHECK (PS_SUPPLYCOST >= 0),
	PS_COMMENT VARCHAR(199),
	PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY),
	FOREIGN KEY (PS_PARTKEY) REFERENCES PART(P_PARTKEY),
	FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY),
	CONSTRAINT check_pk_ps_partkey CHECK (PS_PARTKEY >= 0),
	CONSTRAINT check_pk_ps_suppkey CHECK(PS_SUPPKEY >= 0)
	
);