-- Create REGION Table with Constrains
CREATE TABLE REGION (
	R_REGIONKEY INTEGER NOT NULL PRIMARY KEY,
	R_NAME VARCHAR(25) NOT NULL,
	R_COMMENT VARCHAR (152),
	CONSTRAINT check_pk_region CHECK (R_REGIONKEY >= 0)
);