-- create Customer Table with constraints
CREATE TABLE CUSTOMER(
	C_CUSTKEY INTEGER NOT NULL PRIMARY KEY,
	C_NAME VARCHAR(25),
	C_ADDRESS VARCHAR(40),
	C_NATIONKEY INTEGER NOT NULL,
	C_PHONE CHAR(15),
	C_ACCTBAL DECIMAL,
	C_MKTSEGMENT CHAR(10),
	C_COMMENT VARCHAR(117),
	FOREIGN KEY (C_NATIONKEY) REFERENCES NATION(N_NATIONKEY),
	CONSTRAINT check_postive_custkey CHECK (C_CUSTKEY >= 0)
);