-- create Lineitem Table with constraints
CREATE TABLE LINEITEM(
	L_ORDERKEY INTEGER NOT NULL,
	L_PARTKEY INTEGER NOT NULL,
	L_SUPPKEY INTEGER NOT NULL,
	L_LINENUMBER INTEGER NOT NULL,
	L_QUANTITY DECIMAL NOT NULL CHECK (L_QUANTITY >=0),
	L_EXTENDEDPRICE DECIMAL NOT NULL CHECK (L_EXTENDEDPRICE >=0),
	L_DISCOUNT DECIMAL NOT NULL CHECK(L_DISCOUNT BETWEEN 0 AND 1),
	L_TAX DECIMAL NOT NULL CHECK (L_TAX >=0),
	L_RETURNFLAG CHAR(1),
	L_LINESTATUS CHAR(1),
	L_SHIPDATE DATE,
	L_COMMITDATE DATE,
	L_RECEIPTDATE DATE CHECK (L_SHIPDATE <= L_RECEIPTDATE),
	L_SHIPINSTRUCT CHAR(25),
	L_SHIPMODE CHAR(10),
	L_COMMENT VARCHAR(44),
	PRIMARY KEY (L_ORDERKEY, L_LINENUMBER),
	FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS(O_ORDERKEY),
	FOREIGN KEY (L_PARTKEY, L_SUPPKEY) REFERENCES PARTSUPP(PS_PARTKEY, PS_SUPPKEY)
);