-- Min And Max values for relevant atttributes
SELECT 'REGION' AS TableName, 'R_RGIONKEY' AS ColumnName, MIN(R_REGIONKEY) AS Minvalue, MAX(R_REGIONKEY) AS Maxvalue FROM REGION
UNION ALL
SELECT 'NATION', 'N_NATIONKEY', MIN(N_NATIONKEY), MAX(N_NATIONKEY) FROM NATION
UNION 
SELECT 'PART', 'P_PARTKEY', MIN(P_PARTKEY), MAX(P_PARTKEY) FROM PART
UNION ALL
SELECT 'SUPPLIER', 'S_SUPPKEY', MIN(S_SUPPKEY), MAX(S_SUPPKEY) FROM SUPPLIER
UNION ALL
SELECT 'PARTSUPP', 'PS_PARTKEY', MIN(PS_PARTKEY), MAX(PS_PARTKEY) FROM PARTSUPP
UNION ALL
SELECT 'CUSTOMER', 'C_CUSTKEY', MIN(C_CUSTKEY), MAX(C_CUSTKEY) FROM CUSTOMER
UNION ALL
SELECT 'ORDERS', 'O_ORDERKEY', MIN(O_ORDERKEY), MAX(O_ORDERKEY) FROM ORDERS
UNION ALL
SELECT 'LINEITEM', 'L_ORDERKEY', MIN(L_ORDERKEY), MAX(L_ORDERKEY) FROM LINEITEM;

