
-- Create Materialized View for Q7

CREATE MATERIALIZED VIEW mv_export_import AS
SELECT
  L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS REVENUE,
  N1.N_NAME AS SUPP_NATION,
  N2.N_NAME AS CUST_NATION,
  L_SHIPDATE
FROM SUPPLIER S
JOIN NATION N1 ON S.S_NATIONKEY = N1.N_NATIONKEY
JOIN LINEITEM L ON S.S_SUPPKEY = L.L_SUPPKEY
JOIN ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
JOIN NATION N2 ON C.C_NATIONKEY = N2.N_NATIONKEY;
