-- create Nation Table with constraints
CREATE TABLE NATION (
	N_NATIONKEY INTEGER NOT NULL PRIMARY KEY,
	N_NAME VARCHAR(25) NOT NULL,
	N_REGIONKEY INTEGER NOT NULL,
	N_COMMENT VARCHAR(152),
	FOREIGN KEY (N_REGIONKEY) REFERENCES REGION(R_REGIONKEY),
	CONSTRAINT check_pk_nation CHECK (N_NATIONKEY >= 0)
);