-- Pricing summary Report Query(Q1) before Optimization.
SELECT
	L_RETURNFLAG AS RETURN_FLAG,
	L_LINESTATUS AS LINE_STATUS,
	SUM(L_QUANTITY) AS TOTAL_QUANTITY,
	SUM(L_EXTENDEDPRICE) AS TOTAL_BASE_PRICE,
	SUM(L_EXTENDEDPRICE *(1 - L_DISCOUNT)) AS TOTAL_DISCOUNTED_PRICE,
	SUM(L_EXTENDEDPRICE *(1 - L_DISCOUNT)*(1+ L_TAX)) AS TOTAL_CHARGE,
	AVG(L_QUANTITY) AS AVERAGE_QUANTITY,
	AVG(L_EXTENDEDPRICE) AS AVERAGE_PRICE,
	AVG(L_DISCOUNT) AS AVERAGE_DISCOUNT,
	COUNT(*) AS ORDER_COUNT
FROM 
	LINEITEM
WHERE
	L_SHIPDATE <= DATE '1998-12-01' - INTERVAL '90' DAY
GROUP BY
	L_RETURNFLAG,
	L_LINESTATUS
ORDER BY
	L_RETURNFLAG,
	L_LINESTATUS;

