-- Top supplier qurey Optimised (Q15)

EXPLAIN ANALYZE
SELECT
  S_SUPPKEY,
  S_NAME,
  S_ADDRESS,
  S_PHONE,
  TOTAL_REVENUE
FROM SUPPLIER, REVENUE_Q15
WHERE S_SUPPKEY = SUPPLIER_NO
  AND TOTAL_REVENUE = (
    SELECT MAX(TOTAL_REVENUE) FROM REVENUE_Q15
);
