-- CTE to compute the average account balance once

WITH AVG_ACCTBAL AS (
  SELECT AVG(C_ACCTBAL) AS AVG_BAL
  FROM CUSTOMER
  WHERE C_ACCTBAL > 0.00
    AND SUBSTRING(C_PHONE, 1, 2) IN ('13', '31', '23', '29', '30', '18', '17')
)

SELECT
  COUNTRYCODE,
  COUNT(*) AS NUMBER_CUSTOMER,
  SUM(C_ACCTBAL) AS TOTAL_ACCOUNT_BALANCE
FROM (
  SELECT
    SUBSTRING(C_PHONE, 1, 2) AS COUNTRYCODE, C_ACCTBAL
  FROM
    CUSTOMER
    LEFT JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
    CROSS JOIN AVG_ACCTBAL
  WHERE
    SUBSTRING(c_phone, 1, 2) IN ('13', '31', '23', '29', '30', '18', '17')
    AND C_ACCTBAL > AVG_ACCTBAL.AVG_BAL
    AND O_ORDERKEY IS NULL
) AS CUSTSALE
GROUP BY
  COUNTRYCODE
ORDER BY
  COUNTRYCODE;
