-- Global Sales Opportunity Query Optimized(Q22)

EXPLAIN ANALYZE
WITH CUSTSALE AS (
  SELECT
    SUBSTRING(C_PHONE FROM 1 FOR 2) AS COUNTRYCODE,
    COUNT(*) AS NUMBER_CUSTOMER,
    SUM(C_ACCTBAL) AS TOTAL_ACCOUNT_BALANCE
  FROM CUSTOMER
  WHERE SUBSTRING(C_PHONE FROM 1 FOR 2) IN ('13','31','23','29','30','18','17')
    AND C_ACCTBAL > (
      SELECT AVG(C_ACCTBAL)
      FROM CUSTOMER
      WHERE C_ACCTBAL > 0.00 AND SUBSTRING(C_PHONE FROM 1 FOR 2) IN ('13','31','23','29','30','18','17')
    )
    AND NOT EXISTS (
      SELECT 1 FROM ORDERS WHERE O_CUSTKEY = C_CUSTKEY
    )
  GROUP BY COUNTRYCODE
)
SELECT * FROM CUSTSALE ORDER BY COUNTRYCODE;