--  Local Supplier Volume Optimised (Q5) 

EXPLAIN ANALYZE

SELECT
  N_NAME,
  SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER
JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
JOIN LINEITEM ON O_ORDERKEY = L_ORDERKEY
JOIN SUPPLIER ON L_SUPPKEY = S_SUPPKEY
JOIN NATION ON S_NATIONKEY = N_NATIONKEY
JOIN REGION ON N_NATIONKEY = R_REGIONKEY
WHERE R_NAME = 'ASIA'
  AND O_ORDERDATE >= DATE '1994-01-01'
  AND O_ORDERDATE < DATE '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;