
-- volume shipping query Optimised (Q7)

EXPLAIN ANALYZE
SELECT
  SUPP_NATION,
  CUST_NATION,
  EXTRACT(YEAR FROM L_SHIPDATE) AS L_YEAR,
  SUM(REVENUE) AS SUM_REVENUE
FROM mv_export_import
WHERE ((SUPP_NATION = 'FRANCE' AND CUST_NATION = 'GERMANY')
    OR (SUPP_NATION = 'GERMANY' AND CUST_NATION = 'FRANCE'))
  AND L_SHIPDATE BETWEEN DATE '1995-01-01' AND DATE '1996-12-31'
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;