SELECT 
	COUNT(DISTINCT R_REGIONKEY) AS REGION_KEY,
	MIN(R_REGIONKEY) AS MINIMUM_VALUE,
	MAX(R_REGIONKEY) AS MAXIMUM_VALUE,
	COUNT(DISTINCT R_NAME) AS R_NAMES,
	COUNT(DISTINCT R_COMMENT) AS R_COMMENTS
FROM REGION;