-- Shipping Priority Query (Q3) before Optimization
EXPLAIN ANALYZE
SELECT 
	L_ORDERKEY AS Order_Key,
	SUM (L_EXTENDEDPRICE *(1-L_DISCOUNT)) AS revenue,
	O_ORDERDATE AS Order_date,
	O_SHIPPRIORITY AS ship_priority
FROM
	CUSTOMER,
	ORDERS,
	LINEITEM
WHERE
	C_MKTSEGMENT = 'BUILDING'
	AND C_CUSTKEY = O_CUSTKEY
	AND L_ORDERKEY = O_ORDERKEY
	AND O_ORDERDATE < DATE '1995-03-15'
	AND L_SHIPDATE > DATE '1995-03-15'
GROUP BY
	L_ORDERKEY,
	O_ORDERDATE,
	O_SHIPPRIORITY
ORDER BY
	revenue DESC,
	O_ORDERDATE
LIMIT 10;
