SELECT
    COUNT(DISTINCT S_NATIONKEY) AS DISTINCT_S_NATIONKEY,
    MIN(S_NATIONKEY) AS MIN_S_NATIONKEY,
    MAX(S_NATIONKEY) AS MAX_S_NATIONKEY,

    COUNT(DISTINCT S_SUPPKEY) AS DISTINCT_S_SUPPKEY,
    MIN(S_SUPPKEY) AS MIN_S_SUPPKEY,
    MAX(S_SUPPKEY) AS MAX_S_SUPPKEY,

    COUNT(DISTINCT S_ACCTBAL) AS DISTINCT_S_ACCTBAL,
    MIN(S_ACCTBAL) AS MIN_S_ACCTBAL,
    MAX(S_ACCTBAL) AS MAX_S_ACCTBAL,

    COUNT(DISTINCT S_COMMENT) AS DISTINCT_S_COMMENT,
    COUNT(DISTINCT S_PHONE) AS DISTINCT_S_PHONE,
    COUNT(DISTINCT S_NAME) AS DISTINCT_S_NAME,
    COUNT(DISTINCT S_ADDRESS) AS DISTINCT_S_ADDRESS

FROM SUPPLIER;
